# Generated by Django 5.2.6 on 2025-09-27 04:44

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('status', models.CharField(choices=[('PEND', 'Pendiente'), ('APPR', 'Aprobada'), ('REJ', 'Rechazada')], default='PEND', max_length=5, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='workshop.workorder', verbose_name='OT')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]

