# Generated by Django 5.2.6 on 2025-09-26 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre/Razón Social')),
                ('rut', models.CharField(help_text='Formato: 12345678-5 (sin puntos)', max_length=12, unique=True, verbose_name='RUT')),
                ('client_type', models.CharField(choices=[('NAT', 'Persona Natural'), ('LEG', 'Persona Jurídica')], default='NAT', max_length=3, verbose_name='Tipo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('specialty', models.CharField(blank=True, max_length=120, null=True, verbose_name='Especialidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(help_text='Ej: ABCD12 o XX-YY-11 (sin espacios)', max_length=12, unique=True, verbose_name='Patente')),
                ('brand', models.CharField(blank=True, max_length=60, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=60, null=True, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('vin', models.CharField(blank=True, max_length=30, null=True, verbose_name='VIN')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['plate'],
            },
        ),
    ]
