# Generated by Django 5.2.6 on 2025-09-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre repuesto')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo unitario')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario aplicado a la OT (puede diferir del costo)', max_digits=12, verbose_name='Precio aplicado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='Repuesto')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='workshop.workorder', verbose_name='OT')),
            ],
            options={
                'verbose_name': 'Uso de repuesto en OT',
                'verbose_name_plural': 'Usos de repuestos en OTs',
            },
        ),
    ]
