# Generated by Django 5.2.6 on 2025-09-26 22:54

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha/Hora agendada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nº OT')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('PROG', 'En Proceso'), ('DONE', 'Cerrada'), ('CANC', 'Cancelada')], default='OPEN', max_length=5, verbose_name='Estado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción/solicitud')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.client', verbose_name='Cliente')),
                ('responsible_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.technician', verbose_name='Técnico responsable')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Actividad')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas')),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa $/h')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technician', verbose_name='Técnico')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='workshop.workorder', verbose_name='OT')),
            ],
            options={
                'verbose_name': 'Actividad de reparación (mano de obra)',
                'verbose_name_plural': 'Actividades de reparación',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Detalle diagnóstico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='workshop.workorder', verbose_name='OT')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
    ]

